### ISSUE TITLE
Hi I'm a complete newb send help

### ISSUE THREAD

**Issue by johnny2Boi** [minami1733/fantia_downloader#3]
I'd really like to know how to use this.. What am I supposed to run it with?
It seems the EXE won't run on its own

Do I use this with the browser's .exe? Is this a script for java in-page (whatever that may mean)? Cmd?

I've got no clue even tho I can figure things out most of the times

**Comment by AquaClown** [comment]
fantia_downloader.exe is an executable file for the windows cmd.
As shown in the attached image, specify the required keys and change the other options as needed.
![image](https://user-images.githubusercontent.com/19883161/124461800-0a408700-ddcc-11eb-91b1-6674591271fb.png)

To get the session_id for the key, use the following command in Chrome
1. login to [fantia.jp](https://fantia.jp/)
2. press F12 to open Developer Tools
3. go to the Application tab of Developer Tools
4. open Cookies and select `https://fantia.jp/`
5. `_session_id` is in the Name, copy the Value and specify it as the key.

![image](https://user-images.githubusercontent.com/19883161/124463201-7ff92280-ddcd-11eb-9100-40a16a14ef9f.png)
